server:
  port: 8083
 
spring:
  application:
    name: TRANSACTION-EUREKA
 
  datasource:
    url: jdbc:mysql://localhost:3307/wiprodb
    username: root
    password: Swathika@25
 
  jpa:
    hibernate:
      ddl-auto: update
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka